FROM debian:buster

RUN apt update -y && apt upgrade -y && apt install php-fpm wget unzip -y
RUN mkdir -p /var/www/html \
    && chown -R www-data:www-data /var/www/html

RUN wget https://wordpress.org/latest.zip -P /tmp 
RUN unzip /tmp/latest.zip -d /var/www/html
RUN  rm /tmp/latest.zip
EXPOSE 9000


#WORKDIR /var/www/html/wordpress
CMD ["/usr/sbin/php-fpm7.3", "-F"]
