FROM debian:latest

RUN apt update -y && apt upgrade -y && apt install mariadb-server mariadb-client -y

COPY init-db.sql /docker-entrypoint-initdb.d/
RUN mkdir -p /var/lib/mysql && chown -R mysql:mysql /var/lib/mysql
RUN mkdir -p /run/mysqld && chown -R mysql:mysql /run/mysqld
COPY db_script.sh /db_script.sh
RUN chmod +x /db_script.sh

RUN sed -i -r "s/127.0.0.1/0.0.0.0/1"   /etc/mysql/mariadb.conf.d/50-server.cnf


USER mysql

ENTRYPOINT ["/db_script.sh"]
