version: '3.8'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb  
    ports:
      - "3033:3033"
    restart: always
    volumes: 
      - mariadb:/app
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  
      MYSQL_DATABSE: ${DB_DATABASE}  
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:8000"
      - "4443:4443"  
    volumes: 
      - nginx:/app
    depends_on:
      - mariadb
    networks:
      - backend

volumes:
  nginx:
  mariadb:

networks:
  backend:    
