FROM debian:buster

RUN apt update -y && apt upgrade -y && apt install nginx openssl -y
COPY  ./nginx.conf /etc/nginx/nginx.conf 
COPY ./html /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
