version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    volumes: 
      - wordpress:/var/www/html
    expose:
      - 9000
    networks:
      - backend

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb  
    ports:
      - "3033:3033"
    restart: always
    volumes: 
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  
      MYSQL_DATABSE: ${DB_DATABASE}  
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"  
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html/index.html:/var/www/html/wordpress/index.html
      - wordpress:/var/www/html/
    depends_on:
      - mariadb
    networks:
      - backend

volumes:
  nginx:
  mariadb:
  wordpress:  

networks:
  backend:    
