FROM debian:rc-buggy

RUN apt update -y && apt upgrade -y && apt install nginx openssl -y
#COPY  ./nginx.conf /etc/nginx/nginx.conf 
#COPY ./html /usr/share/nginx/html
RUN mkdir -p ./certs
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./certs/nginx.key -out ./certs/nginx.crt -subj "/C=SP/L=MA/O=42/OU=student/CN=ahammoud.42.fr"


CMD ["nginx", "-g", "daemon off;"]
