version: '3.8'

services:
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile.wordpress
    volumes: 
      - wordpress:/var/www/html
      - ./requirements/wordpress/conf/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - mariadb
 

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile.mariadb  
    ports:
      - "3306:3306"
    restart: always
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - backend
    env_file:
      - .env


  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"  
    volumes: 
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - wordpress:/var/www/html/
    depends_on:
      - mariadb
    networks:
      - backend
    env_file:
      - .env


volumes:
  nginx:
  mariadb:
  wordpress:  

networks:
  backend:
